version: '3'
services:
    server:
        build:
            context: server
        container_name: server
        restart: always
        ports:
            - 25565:25565
        volumes:
            - worlds:/opt/server/worlds
            - ./logs:/opt/server/logs
        logging:
            driver: 'json-file'
            options:
                max-size: '200k'
                max-file: '10'
        stdin_open: true
        tty: true
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 10G
                reservations:
                    cpus: '1'
                    memory: 10M
    ip_detector:
        build:
            context: ip_detector
        container_name: ip_detector
        restart: always
        volumes:
            - ip:/ip

volumes:
    worlds:
    ip:
