version: '3'
services:
    queue:
        image: rabbitmq:3-management
        container_name: queue
        restart: always
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - rabbitmq:/var/lib/rabbitmq
            - ./logs/queue:/var/log/rabbitmq
    mcserver:
        build:
            context: .
            dockerfile: mcserver/Dockerfile
        container_name: mcserver
        restart: always
        ports:
            - '25565:25565'
            - '8100:8100'
            - '9100:9100'
        volumes:
            - worlds:/opt/mcserver/worlds
            - gsit:/opt/mcserver/plugins/GSit/data
            - maps:/opt/mcserver/plugins/bluemap/web
            - tabtps:/opt/mcserver/plugins/tabtps/userdata
            - ./backups:/opt/mcserver/plugins/Backuper/Backups
            - ./logs/mcserver:/opt/mcserver/logs
            - ./logs/bluemap:/bluemap/logs
        logging:
            driver: 'json-file'
            options:
                max-size: '200k'
                max-file: '10'
        stdin_open: true
        tty: true
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 10G
                reservations:
                    cpus: '1'
                    memory: 10M
    ip_detector:
        build:
            context: .
            dockerfile: ip_detector/Dockerfile
        container_name: ip_detector
        restart: always
        volumes:
            - ./ip.txt:/ip/ip.txt
            - ./logs/ip_detector:/logs
        depends_on:
            - queue
    announcer:
        build:
            context: .
            dockerfile: announcer/Dockerfile
        container_name: announcer
        restart: always
        depends_on:
            - queue
        volumes:
            - ./logs/announcer:/logs
        env_file:
            - ./.env
    # grafana:
    #     image: grafana/agent:latest
    #     container_name: grafana
    #     restart: always
    #     depends_on:
    #         - mcserver
    #     security_opt:
    #         - no-new-privileges:true
    #     volumes:
    #         - ./grafana/agent-config.yml:/etc/agent-config/agent.yml
    #     # entrypoint:
    #     #     - /bin/agent
    #     #     - -config.file=/etc/agent-config/agent.yml
    #     #     - -prometheus.wal-directory=/tmp/agent/wal
    #     networks:
    #         - prometheus
    # Example: BACKUP='04.08.2023\ 22:14:24' docker-compose up --build load_backup
    load_backup:
        image: alpine:latest
        container_name: load_backup
        volumes:
            - worlds:/opt/work/worlds
            - ./backups:/opt/work/backups
        working_dir: /opt/work
        entrypoint:
            - sh
            - -c
            - |
                unzip ./backups/${BACKUP}.zip -d ./temp \
                && rm -rf ./worlds/* \
                && mv ./temp/worlds/* ./worlds \
                && rm -rf ./temp
volumes:
    worlds:
    rabbitmq:
    gsit:
    maps:
    tabtps:

networks:
    prometheus:
        external: true
