metrics:
  global:
    scrape_interval: 60s
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: node
        static_configs:
        - targets: ['mcserver:9100']
    remote_write:
      - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
        basic_auth:
          username: 1105884
          password: glc_eyJvIjoiOTA2NzMxIiwibiI6ImdvaW5nLXRvLWNyYWZ0IiwiayI6Im1MZXgwdjZRNjE4QzQ3RTBTazNleG00dSIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
