[project]
name = "mcqueue"
version = "1.0.0"
description = "For publishing and receiving messages"
requires-python = ">=3.10"
dependencies = [
    "pika==1.3.2",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"